title: "Day one/One day"
theme: slate  # Aquí defines el tema para todo el sitio
permalink: /
markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
